const i18n = {
    "en": {
        "tagline": "Multi-Gene HR Variant Classifier • 120 Features from 8 Data Sources • ESM-2 Protein LM Embeddings • SHAP Explained",
        "stat_mcc": "MCC",
        "stat_bal_acc": "Balanced Acc",
        "stat_model": "Ensemble",
        "stat_genes": "HR Genes",
        "upload_title": "Upload VCF",
        "tgt_gene_ctx": "Target Gene Context",
        "drop_vcf": "Drop your VCF file here",
        "or_click": "or click to browse · .vcf format",
        "manual_entry": "Manual Entry",
        "tgt_gene": "Target Gene",
        "cdna_pos": "cDNA Position",
        "ref_aa": "Reference AA",
        "alt_aa": "Alternate AA",
        "mut_type": "Mutation Type",
        "mutation": "Mutation",
        "mut_opt": "(optional)",
        "analyze_btn": "Analyze Variant",
        "why_shap": "Why This Prediction? — SHAP Feature Attribution",
        "acmg_ev": "ACMG Evidence",
        "pathogenic": "Pathogenic",
        "benign": "Benign",
        "legend_path": "Pathogenic",
        "legend_ben": "Benign",
        "fetch_clinvar": "Fetch Live ClinVar",
        "fetch_gnomad": "Fetch Live gnomAD",
        "vcf_batch": "VCF Batch Results",
        "analyzing": "Analyzing variants...",
        "tb_hgvs": "HGVS",
        "tb_cdna": "cDNA",
        "tb_aa": "AA Change",
        "tb_mut": "Mutation",
        "tb_pred": "Prediction",
        "tb_prob": "Probability",
        "remove_variant": "Remove variant",
        "info1_t": "Universal Base Models",
        "info1_d": "Multi-gene HR Deep Neural Network & XGBoost ensemble trained on 19,000+ ClinVar & gnomAD HR missense variants with isotonic probability calibration. Resolves 5 genes seamlessly.",
        "info2_t": "120 Features",
        "info2_d": "BLOSUM62 substitution scores, ESM-2 language model embeddings, MAVE functional assays, EVE evolutionary scores, PhyloP conservation, SpliceAI splice predictions, AlphaFold structural features, and gnomAD population frequencies.",
        "info3_t": "SHAP Explanations",
        "info3_d": "Every prediction shows which features pushed it toward pathogenic or benign, using SHAP values extracted from the XGBoost model.",
        "footer1": "Research use only · Not a diagnostic tool · Germline variants only",
        "footer2": "Germline only: the model was trained exclusively on inherited (germline) variants from ClinVar and gnomAD. Somatic (tumor-acquired) mutations have different properties and are not supported.",
        "footer3": "ACMG evidence codes are computational approximations and do not replace expert clinical curation.",
        "footer4": "Privacy: no variant data, queries, or personal information is stored, logged, or transmitted to third parties. All predictions are computed on the server and discarded after the response.",
        "err_vcf_only": "Only .vcf files are accepted",
        "err_vcf_failed": "VCF upload failed",
        "err_backend": "Could not reach the backend — make sure the server is running.",
        "err_invalid_ref": "Invalid Reference AA",
        "err_invalid_alt": "Invalid Alternate AA",
        "err_cdna_range": "cDNA position must be between 1 and",
        "err_enter_cdna": "Please enter a cDNA sequence position",
        "err_enter_ref": "Please enter a Reference Amino Acid (e.g. Arg)",
        "err_enter_alt": "Please enter an Alternate Amino Acid (e.g. Cys)",
        "err_timeout": "Request timed out — the backend may be overloaded. Please try again.",
        "err_no_results": "No prediction results returned from the server.",
        "vcf_processing": "Processing VCF file...",
        "vcf_complete": "VCF analysis complete",
        "vcf_variants_found": "variants analyzed",
        "download_csv": "Download CSV",
        "shap_show_all": "Show All Features",
        "shap_show_top": "Show Top 8 Only",
        "download_pdf": "Download PDF Report",
        "history_title": "Recent Analyses",
        "history_clear": "Clear",
        "download_json": "Export JSON",
        "compare_btn": "Compare",
        "stat_sw_auc": "Sample-Wtd AUC",
        "stat_macro_auc": "Macro-Avg AUC",
        "tip_roc_auc": "Sample-weighted Area Under the ROC curve. Measures how well the model separates pathogenic from benign variants. 1.0 = perfect, 0.5 = random guess. Weighted by gene representation (BRCA2 = 52% of test set).",
        "tip_macro_auc": "Macro-averaged AUC across all 5 genes (unweighted).",
        "tip_mcc": "Matthew's Correlation Coefficient. A balanced metric from -1 to +1 that accounts for true/false positives and negatives. Considered the most reliable single metric for binary classification.",
        "tip_bal_acc": "Average of sensitivity (true pathogenic rate) and specificity (true benign rate). Unaffected by class imbalance unlike raw accuracy.",
        "tip_ensemble": "XGBoost + Multi-Layer Perceptron neural network with gene-adaptive weights and isotonic calibration. Weight ratios are optimized per gene on calibration data for best performance.",
        "tip_hr_genes": "Homologous Recombination DNA repair genes: BRCA1, BRCA2, PALB2, RAD51C, RAD51D. Mutations in these genes cause hereditary breast, ovarian, and other cancers.",
        "tip_ref_aa": "The original (wild-type) amino acid at this position. Use 3-letter codes: Ala, Arg, Asn, Asp, Cys, Glu, Gly, His, Ile, Leu, Lys, Met, Phe, Pro, Ser, Thr, Trp, Tyr, Val.",
        "tip_alt_aa": "The mutant amino acid that replaced the original. This is the variant you want to classify as pathogenic or benign.",
        "tip_acmg": "American College of Medical Genetics classification criteria. PP/PM/PS = evidence for pathogenic. BP/BS/BA = evidence for benign. These are computational approximations.",
        "tip_shap": "SHAP (SHapley Additive exPlanations) shows how each biological feature pushed the prediction toward pathogenic (+) or benign (-). Longer bars = stronger influence on this specific variant. Note: SHAP values explain which features influenced this prediction. They do not imply biological causation.",
        "tip_clinvar": "NCBI ClinVar database. Queries the latest clinical significance classification for this variant from submitting labs worldwide.",
        "tip_gnomad": "Genome Aggregation Database. Shows how often this variant appears across ~807K sequenced individuals (~1.6M alleles) from diverse populations.",
        "tip_eve": "Evolutionary model of Variant Effect. Unsupervised model trained on 140K+ protein sequences across evolution. Score 0-1, >0.5 = likely pathogenic. Available for BRCA1, PALB2, RAD51C, RAD51D.",
        "tip_mave": "Multiplexed Assay of Variant Effect. Wet-lab measurement of protein function. Lower scores = loss of function = likely pathogenic.",
        "tip_phylop": "Phylogenetic P-value measuring evolutionary conservation across 100 vertebrate species. Higher = more conserved = mutations more likely damaging.",
        "tip_3d_structure": "AlphaFold-predicted protein structure. Shows if the mutation site is buried inside the protein, on the surface, or in contact with DNA.",
        "tip_blosum62": "Amino acid substitution score from the BLOSUM62 matrix. Negative = rare/damaging substitution. Positive = common/tolerated.",
        "tip_volume_diff": "Difference in physical volume between original and mutant amino acid (in cubic angstroms). Large changes disrupt protein packing.",
        "tip_hydro_diff": "Difference in hydrophobicity (water-repelling tendency). Large changes can flip a residue from buried to exposed or vice versa.",
        "tip_charge_change": "Whether the mutation changes the electric charge of the amino acid (e.g. positive to negative). Charge changes often disrupt protein interactions.",
        "tip_nonsense": "Whether this mutation creates a premature stop codon (Ter), truncating the protein. Almost always pathogenic.",
        "tip_critical_domain": "Whether the mutation falls in a known functional domain (e.g. DNA binding, PALB2 binding, BRC repeats). Domain mutations are more likely damaging.",
        "mc_title": "Model Card & Limitations",
        "mc_intended_use": "Intended Use",
        "mc_intended_use_d": "Research-grade variant classification for missense, nonsense, and truncating variants in 5 Homologous Recombination DNA repair genes (BRCA1, BRCA2, PALB2, RAD51C, RAD51D). Missense variants use ML ensemble; truncating variants (frameshift, indels, duplications) use rule-based Tier 1 classification. Intended as a decision-support tool, not a standalone diagnostic.",
        "mc_training_data": "Training Data",
        "mc_training_data_d": "19,223 variants: 18,738 from ClinVar (reviewed/expert-panel classifications) + 485 gnomAD proxy-benign (AC ≥ 2 in ~1.6M alleles). 60/20/20 split with gene × label stratification. RANDOM_STATE=42.",
        "mc_architecture": "Architecture",
        "mc_architecture_d": "XGBoost + Multi-Layer Perceptron blended ensemble with gene-adaptive weights and isotonic calibration trained on a held-out calibration set. 120 engineered features from 8 data sources.",
        "mc_performance": "Performance",
        "mc_performance_d": "ROC-AUC: 0.985 · MCC: 0.928 · Balanced Accuracy: 96.5%. 10-fold CV: 0.9858 ± 0.0021. Outperforms REVEL (0.725), BayesDel (0.721), CADD (0.539) on same test set.*",
        "mc_perf_caveat": "* Evaluated on SteppeDNA test set. General-purpose tools not trained on same distribution.",
        "mc_limitations": "Known Limitations",
        "mc_lim1": "Non-BRCA2 genes have smaller training sets and lower per-gene AUC (PALB2: 0.605, RAD51C: 0.785)",
        "mc_lim2": "Copy number variants (CNVs) are not classified. Splice-site, in-frame indel, and synonymous variants use rule-based classification (not the ML model). Truncating variants (nonsense, frameshift) use Tier 1 protocol",
        "mc_lim3": "Model may underperform on novel variants with no population frequency data",
        "mc_lim4": "Probabilities are clipped to [1%, 99%] — the model never claims absolute certainty",
        "mc_lim5": "Compound heterozygosity warning is provided in VCF batch analysis, but does not perform phasing; variants require segregation study to determine cis/trans configuration. Polygenic interactions are not modeled",
        "mc_lim6": "Training data predominantly from populations of European descent; however, 90.8% of features are population-independent. Population-calibrated ACMG rules and widened CIs mitigate frequency bias for Central Asian variants",
        "mc_lim7": "ClinVar classifications evolve over time; training labels may not reflect the latest expert consensus",
        "mc_sota_note": "Evaluated on SteppeDNA's held-out test set. REVEL, BayesDel, and CADD are general-purpose predictors. Independent benchmark AUC: 0.750–0.801 (no training overlap). Overall metrics weighted by gene prevalence (BRCA2: 52% of test set).",
        "acmg_approx_label": "Computational approximation — not a validated ACMG classification. Implements 11 of 28 ACMG criteria.",
        "gene_reliability_warn": "Gene-specific model reliability",
        "vus_guidance": "This variant falls in the uncertain range. Recommend: (1) functional assay validation, (2) family segregation study, (3) ClinVar monitoring for reclassification, (4) consultation with genetic counselor.",
        "population_label": "Population",
        "pop_global": "Global (default)",
        "founder_badge": "Known Founder Mutation",
        "founder_freq": "Frequency",
        "mc_ethics": "Ethical Considerations",
        "mc_eth1": "Not validated for clinical diagnostic use — all predictions require expert review",
        "mc_eth2": "Training data is primarily from populations of European descent; population-calibrated ACMG rules and widened confidence intervals are applied for underrepresented ancestries",
        "mc_eth3": "ACMG evidence codes are computational approximations, not expert classifications",
        "mc_eth4": "Should not be used as the sole basis for clinical decisions about patient care",
        "vcf_type_col": "Type",
        "splice_canonical": "Canonical Splice Site",
        "splice_near": "Near Splice Site",
        "inframe_indel": "In-Frame Indel",
        "synonymous_label": "Synonymous",
        "compound_het_title": "Compound Heterozygosity Warning",
        "compound_het_no_gt": "Note: VCF file did not contain genotype (GT) data. Warning based on variant count.",
        "skipped_title": "Skipped Variants",
        "variants_analyzed": "Classified",
        "umap_title": "Variant Landscape (UMAP)",
        "umap_subtitle": "Your variant estimated among 5,000 training variants",
        "umap_leg_path": "Pathogenic",
        "umap_leg_ben": "Benign",
        "umap_leg_query": "Your Variant",
        "cmp_title": "Variant Comparison",
        "offline_msg": "Server is starting up — predictions will be available shortly.",
        "online_msg": "Connected",
        "viewer3d_title": "3D Protein Structure",
        "viewer3d_subtitle": "Mutation position highlighted on the AlphaFold-predicted structure",
        "viewer3d_loading": "Loading 3D structure...",
        "viewer3d_error_load": "Could not load the 3D structure for this gene. The protein may be too large for browser rendering.",
        "viewer3d_error_brca2": "BRCA2 structure (3,418 AA) is too large for interactive browser rendering. Use the PyMOL or UCSF ChimeraX desktop tools for large structures.",
        "pergene_title": "Per-Gene ROC-AUC Performance",
        "pergene_footnote": "Overall AUC (0.985) is weighted by gene representation. BRCA2 comprises 52% of the test set. Evaluated on a held-out 20% stratified test split.",
        "temporal_footnote": "Non-BRCA2 temporal AUCs (0.51–0.61) indicate limited generalization over time for data-scarce genes.",
        "ensemble_weights_label": "Ensemble",
        "ensemble_weights_tip": "Gene-adaptive blend of XGBoost and MLP models, optimized per gene on calibration data. Different genes may use different weight ratios for best performance.",
        "feature_coverage_label": "Feature Coverage",
        "feature_coverage_tip": "Percentage of the 120 model features with non-zero values for this variant. Lower coverage means less data was available, which may reduce prediction reliability.",
        "data_support_label": "Training Data Support",
        "data_support_tip": "Measures how much training data exists near this variant position. HIGH = >100 nearby training variants, MODERATE = 10-100, LOW = <10. More nearby data means more reliable predictions.",
        "data_support_nearby": "nearby",
        "data_support_same_subst": "same subst.",
        "data_support_in_domain": "in known domain",
        "data_support_outside_domain": "outside known domain",
        "bootstrap_ci_label": "Bootstrap CI",
        "bootstrap_ci_tip": "Confidence interval computed from 50 bootstrap XGBoost models. Narrower CI = more reliable prediction. Width reflects training data density near this variant.",
        "research_priorities_title": "Research Priorities: Recommended for Functional Validation",
        "research_priorities_desc": "Variants ranked by their value for functional validation using query-by-committee model disagreement, gene data scarcity, and positional novelty. Higher priority variants have greater potential to improve the model when experimentally characterized.",
        "research_priorities_note": "QBC = Query By Committee (|XGB - MLP|). Priority = QBC x gene scarcity x positional novelty.",
        "rp_variant": "Variant",
        "rp_priority": "Priority",
        "rp_qbc": "QBC Score",
        "rp_prediction": "Current Pred.",
        "rp_nearby": "Nearby Train.",
        "rp_reason": "Reason",
        "contrastive_title": "Contrastive Explanation",
        "contrastive_tip": "Shows the nearest training variant with the opposite classification. The key differences highlight which features most distinguish this variant from its nearest opposite-class neighbor.",
        "contrastive_compared_to": "Compared to the nearest",
        "contrastive_variant_word": "variant",
        "contrastive_predicted": "predicted",
        "contrastive_differs_in": "this variant differs most in",
        "contrastive_distance": "distance",
        "contrastive_query": "Query",
        "contrastive_contrast": "Contrast",
        "contrastive_imp_high": "High",
        "contrastive_imp_moderate": "Moderate",
        "contrastive_imp_low": "Low",
        "conformal_coverage_label": "90% Coverage Guarantee",
        "conformal_tip": "Split conformal prediction produces a set of classes guaranteed to contain the true label with 90% probability (distribution-free). A singleton set (one class) means high certainty; a larger set honestly communicates uncertainty.",
        "conformal_singleton": "Confident prediction — single class in conformal set",
        "conformal_multi": "Uncertain — multiple classes in conformal set",
        "sota_comparison_title": "Per-Gene SOTA Comparison",
        "sota_col_gene": "Gene",
        "sota_col_steppdna": "SteppeDNA",
        "sota_col_best_sota": "Best SOTA",
        "sota_col_winner": "Winner",
        "sota_footnote": "* All tools evaluated on SteppeDNA\u2019s held-out test set (methodological advantage). REVEL/BayesDel/CADD scored 72\u201373% of variants. Independent benchmark AUC: 0.750\u20130.801 (no training overlap).",
        "sota_pergene_note": "Per-gene SOTA AUCs evaluated on SteppeDNA v5.4 test set. Scores sourced from dbNSFP; tools that could not score a variant were excluded from that gene\u2019s comparison.",
        "method_ml": "ML Ensemble",
        "method_rule": "Rule-Based",
        "am_title": "AlphaMissense Label Leakage Discovery",
        "am_explanation": "AlphaMissense (Cheng et al. 2023) was partially trained on ClinVar labels, creating indirect label circularity. Ablation testing revealed that removing AlphaMissense features <strong>improved</strong> AUC for 3 of 5 genes. AlphaMissense was removed in v5.4.",
        "am_with": "With AlphaMissense",
        "am_without": "Without (v5.4)",
        "am_callout": "3 of 5 genes improved after removing AlphaMissense \u2014 confirming indirect ClinVar label leakage. Overall AUC: 0.9846 \u2192 0.9853 (no loss).",
        "am_footnote": "Ablation study conducted with XGBoost-only on the pre-v5.4 model configuration. Per-gene AUC values differ from the final v5.4 XGBoost+MLP ensemble.",
        "eq_title": "Population Equity Analysis",
        "eq_perf_title": "Model Performance by Ancestry",
        "eq_ancestry_caveat": "Proxy assignment by highest gnomAD sub-population AF \u2014 not self-reported ancestry. 84% of variants had no assignable population. Small sample sizes limit interpretation.",
        "eq_vus_title": "VUS Resolution Capacity by Gene",
        "eq_high": "High confidence",
        "eq_moderate": "Moderate",
        "eq_low": "Low \u2014 interpret with caution",
        "eq_pm2_title": "PM2 Evidence Disparity by Population",
        "eq_col_pop": "Population",
        "eq_col_pm2": "Variants meeting PM2",
        "eq_col_diff": "Difference vs NFE",
        "eq_footnote": "PM2 (absent from population databases) is triggered more often for non-European populations due to lower representation in gnomAD. This can inflate pathogenicity evidence for underrepresented groups.",
        "eq_mitigation_title": "How SteppeDNA Addresses Population Bias",
        "eq_mit1": "<strong>90.8% frequency-independent architecture</strong> \u2014 109 of 120 prediction features use universal biological signals (protein structure, evolutionary conservation, protein language models) that work equally for any population",
        "eq_mit2": "<strong>Population-calibrated ACMG rules</strong> \u2014 PM2 evidence is automatically withheld for Kazakh/Central Asian patients (gnomAD has ~0% Central Asian representation; \u201cabsent from controls\u201d means \u201cnever checked\u201d). BA1/BS1 benign thresholds are relaxed 2\u00d7 to prevent premature benign calls from sparse data",
        "eq_mit3": "<strong>Founder mutation integration (PS4)</strong> \u2014 7 known Kazakh founder mutations from published cancer genetics studies are recognized as formal ACMG strong pathogenic evidence, not just annotations",
        "eq_mit4": "<strong>Honest uncertainty</strong> \u2014 confidence intervals are automatically widened (\u00d71.5) for underrepresented populations, preventing overconfident misclassification",
        "fb_title": "Kazakh Founder Mutations \u2014 Tool Comparison",
        "fb_col_variant": "Variant",
        "fb_col_gene": "Gene",
        "fb_col_freq": "Freq (KZ)",
        "fb_frameshift": "Frameshift \u2014 N/A (SteppeDNA, REVEL)",
        "fb_splice": "Splice site \u2014 N/A (SteppeDNA, REVEL)",
        "fb_footnote": "CADD scores are on PHRED scale (not directly comparable to probability scores). REVEL and BayesDel evaluate missense variants only; SteppeDNA requires amino acid input and cannot score frameshifts or splice variants. CADD can score all variant types but scores for indel/splice founders were not retrieved.",
        "pop_compare_title": "Population Impact on ACMG Evidence",
        "pop_gained": "New evidence (population-specific)",
        "pop_lost": "Removed vs global",
        "pop_changed": "Changed rationale",
        "pop_no_diff": "No difference in ACMG evidence",
    },
    "kk": {
        "tagline": "Multi-Gene HR варианттар классификаторы • 8 деректер көзінен 120 белгі • ESM-2 ақуыз тілдік модель эмбеддингтері • SHAP түсіндірмелері",
        "stat_mcc": "MCC",
        "stat_bal_acc": "Теңгерілген дәлдік",
        "stat_model": "Ансамбль",
        "stat_genes": "HR гендер",
        "upload_title": "VCF файлын жүктеу",
        "tgt_gene_ctx": "Мақсатты ген контексті",
        "drop_vcf": "VCF файлын осында тастаңыз",
        "or_click": "немесе таңдау үшін басыңыз · .vcf пішімі",
        "manual_entry": "Қолмен енгізу",
        "tgt_gene": "Мақсатты ген",
        "cdna_pos": "cDNA позициясы",
        "ref_aa": "Референттік АҚ",
        "alt_aa": "Альтернативті АҚ",
        "mut_type": "Мутация түрі",
        "mutation": "Мутация",
        "mut_opt": "(міндетті емес)",
        "analyze_btn": "Нұсқаны талдау",
        "why_shap": "Неліктен мұндай болжам? — SHAP белгілерінің үлесі",
        "acmg_ev": "ACMG дәлелдері",
        "pathogenic": "Патогендік",
        "benign": "Қатерсіз",
        "legend_path": "Патогендік",
        "legend_ben": "Қатерсіз",
        "fetch_clinvar": "ClinVar деректерін алу",
        "fetch_gnomad": "gnomAD деректерін алу",
        "vcf_batch": "VCF топтама нәтижелері",
        "analyzing": "Варианттар талдануда...",
        "tb_hgvs": "HGVS",
        "tb_cdna": "cDNA",
        "tb_aa": "АҚ Өзгерісі",
        "tb_mut": "Мутация",
        "tb_pred": "Болжам",
        "tb_prob": "Ықтималдық",
        "remove_variant": "Вариантты жою",
        "info1_t": "Әмбебап негізгі модельдер",
        "info1_d": "Терең нейрондық желі және XGBoost ансамблі изотониялық калибрлеу арқылы 19 000-нан астам ClinVar және gnomAD HR миссенс-варианттарында оқытылған. 5 ген үшін варианттарды дәл жіктейді.",
        "info2_t": "120 белгі",
        "info2_d": "BLOSUM62 алмастыру матрицасы, ESM-2 тілдік модель эмбеддингтері, MAVE функционалдық зерттеулері, EVE эволюциялық ұпайлары, PhyloP консервация, SpliceAI сплайсинг болжамдары, AlphaFold құрылымдық ерекшеліктері және gnomAD популяциялық жиіліктер.",
        "info3_t": "SHAP түсіндірмелері",
        "info3_d": "Әрбір болжам XGBoost моделінен алынған SHAP мәндері арқылы қандай белгілердің патогендік немесе қатерсіз нәтижеге әсер еткенін көрсетеді.",
        "footer1": "Тек зерттеу мақсатында · Диагностикалық құрал емес · Тек герминалды варианттар",
        "footer2": "Тек герминалды: модель ClinVar және gnomAD деректеріндегі тұқым қуалайтын (герминалды) варианттармен ғана оқытылды. Соматикалық (ісіктен пайда болған) мутациялар қолдаудан тыс.",
        "footer3": "ACMG дәлелдеме кодтары есептеулік болжамдар болып табылады және сараптамалық клиникалық курацияны алмастырмайды.",
        "footer4": "Құпиялылық: ешқандай вариант деректері, сұраулар немесе жеке ақпарат сақталмайды, тіркелмейді немесе үшінші тарапқа жіберілмейді. Барлық болжамдар серверде есептеліп, жауаптан кейін жойылады.",
        "err_vcf_only": "Тек .vcf файлдары қабылданады",
        "err_vcf_failed": "VCF жүктелу қатесі",
        "err_backend": "Серверге қосылу мүмкін болмады — сервер іске қосылғанын тексеріңіз.",
        "err_invalid_ref": "Жарамсыз референттік АҚ",
        "err_invalid_alt": "Жарамсыз альтернативті АҚ",
        "err_cdna_range": "cDNA позициясы 1 мен аралығында болуы керек",
        "err_enter_cdna": "cDNA тізбегінің позициясын енгізіңіз",
        "err_enter_ref": "Референттік амин қышқылын енгізіңіз (мыс. Arg)",
        "err_enter_alt": "Альтернативті амин қышқылын енгізіңіз (мыс. Cys)",
        "err_timeout": "Сұраныс уақыты бітті — сервер шамадан тыс жүктелген болуы мүмкін. Қайтадан байқап көріңіз.",
        "err_no_results": "Серверден болжам нәтижелері алынбады.",
        "vcf_processing": "VCF файлы өңделуде...",
        "vcf_complete": "VCF талдауы аяқталды",
        "vcf_variants_found": "вариант талданды",
        "download_csv": "CSV жүктеу",
        "shap_show_all": "Барлық белгілерді көрсету",
        "shap_show_top": "Тек үздік 8-ді көрсету",
        "download_pdf": "PDF есебін жүктеу",
        "history_title": "Соңғы талдаулар",
        "history_clear": "Тазалау",
        "download_json": "JSON экспорттау",
        "compare_btn": "Салыстыру",
        "stat_sw_auc": "Үлгі-өлш. AUC",
        "stat_macro_auc": "Макро-орт. AUC",
        "tip_roc_auc": "Үлгі бойынша өлшенген ROC қисығы астындағы аудан. Модельдің патогенді нұсқаларды зиянсыздардан қаншалықты жақсы ажыратқанын өлшейді. 1.0 = тамаша, 0.5 = кездейсоқ болжам. Ген таралуына байланысты өлшенген (BRCA2 = тест жиынының 52%).",
        "tip_macro_auc": "Барлық 5 ген бойынша макро-орташа AUC (өлшенбеген).",
        "tip_mcc": "Мэтьюс корреляция коэффициенті. -1-ден +1-ге дейінгі теңгерімді көрсеткіш, шын/жалған оң және теріс нәтижелерді ескереді. Бинарлық жіктеудің ең сенімді көрсеткіші.",
        "tip_bal_acc": "Сезімталдық (патогенді дұрыс анықтау) пен ерекшеліктің (зиянсызды дұрыс анықтау) орташа мәні. Класс теңсіздігіне тәуелді емес.",
        "tip_ensemble": "XGBoost + көп қабатты перцептрон, ген-адаптивті салмақтармен және изотоникалық калибрлеумен. Салмақ арақатынасы калибрлеу деректерінде ген бойынша оңтайландырылған.",
        "tip_hr_genes": "Гомологиялық рекомбинация ДНҚ жөндеу гендері: BRCA1, BRCA2, PALB2, RAD51C, RAD51D. Бұл гендердегі мутациялар тұқым қуалайтын сүт безі, аналық без қатерлі ісігін тудырады.",
        "tip_ref_aa": "Бұл позициядағы бастапқы (жабайы түр) амин қышқылы. 3 әріпті кодтарды қолданыңыз: Ala, Arg, Asn, Asp, Cys, Glu, Gly, His, Ile, Leu, Lys, Met, Phe, Pro, Ser, Thr, Trp, Tyr, Val.",
        "tip_alt_aa": "Бастапқысын алмастырған мутантты амин қышқылы. Бұл сіз патогенді немесе зиянсыз деп жіктегіңіз келетін нұсқа.",
        "tip_acmg": "Американдық медициналық генетика колледжінің жіктеу критерийлері. PP/PM/PS = патогенділік дәлелдері. BP/BS/BA = зиянсыздық дәлелдері. Бұлар есептеулік жуықтаулар.",
        "tip_shap": "SHAP әрбір биологиялық белгінің болжамға қалай әсер еткенін көрсетеді: патогенді (+) немесе зиянсыз (-) жаққа. Жолақ ұзын болған сайын — әсер күшті. Ескерту: SHAP мәндері болжамға қандай белгілер әсер еткенін түсіндіреді. Олар биологиялық себептілікті білдірмейді.",
        "tip_clinvar": "NCBI ClinVar деректер базасы. Бүкіл әлемдегі зертханалардан осы нұсқаның соңғы клиникалық жіктелуін сұрайды.",
        "tip_gnomad": "Геномдарды біріктіру деректер базасы. Бұл нұсқаның әр түрлі популяциялардан ~807 мың секвенцияланған адамдарда (~1,6 млн аллельде) қаншалықты жиі кездесетінін көрсетеді.",
        "tip_eve": "Вариант әсерінің эволюциялық моделі. Эволюция бойынша 140 мыңнан астам ақуыз тізбегінде оқытылған бақылаусыз модель. Ұпай 0-1, >0.5 = патогенді. BRCA1, PALB2, RAD51C, RAD51D үшін қолжетімді.",
        "tip_mave": "Вариант әсерінің мультиплексті зерттеуі. Зертханалық жағдайда ақуыз функциясын өлшеу. Төмен балл = функция жоғалуы = патогенді.",
        "tip_phylop": "100 омыртқалы түрде эволюциялық консервацияны өлшейтін филогенетикалық P-мән. Жоғары = консервацияланған = мутациялар зиянды болуы мүмкін.",
        "tip_3d_structure": "AlphaFold болжаған ақуыз құрылымы. Мутация орны ақуыз ішінде, бетінде немесе ДНҚ-мен жанасуда екенін көрсетеді.",
        "tip_blosum62": "BLOSUM62 матрицасынан алынған амин қышқылы алмастыру балы. Теріс = сирек/зиянды. Оң = жиі/зиянсыз.",
        "tip_volume_diff": "Бастапқы және мутантты амин қышқылы арасындағы көлем айырмашылығы. Үлкен өзгерістер ақуыз орамасын бұзады.",
        "tip_hydro_diff": "Гидрофобтылық айырмашылығы (суды тебу қабілеті). Үлкен өзгерістер аминқышқылын жасырыннан ашыққа ауыстыруы мүмкін.",
        "tip_charge_change": "Мутация амин қышқылының электр зарядын өзгертеді ме (мыс. оңнан теріске). Заряд өзгерістері ақуыз әрекеттестіктерін жиі бұзады.",
        "tip_nonsense": "Мутация мерзімінен бұрын тоқтату кодонын (Ter) жасайды ма, ақуызды қысқартады. Барлық жағдайда дерлік патогенді.",
        "tip_critical_domain": "Мутация белгілі функционалдық доменде ме (мыс. ДНҚ байланысу, PALB2 байланысу, BRC қайталанулары). Домен мутациялары зиянды болуы мүмкін.",
        "mc_title": "Модель картасы және шектеулер",
        "mc_intended_use": "Мақсатты қолдану",
        "mc_intended_use_d": "5 гомологиялық рекомбинация ДНҚ жөндеу гендеріндегі (BRCA1, BRCA2, PALB2, RAD51C, RAD51D) миссенс, нонсенс және қысқартатын варианттарды зерттеу деңгейінде жіктеу. Миссенс варианттар ML ансамблін, қысқартатын варианттар (фреймшифт, инделдер, дупликациялар) ережелер негізіндегі Tier 1 жіктеуді пайдаланады. Шешім қабылдауға көмекші құрал, жеке диагностика емес.",
        "mc_training_data": "Оқыту деректері",
        "mc_training_data_d": "19 223 вариант: ClinVar-дан 18 738 (сараптамалық жіктелулер) + gnomAD-тан 485 прокси-зиянсыз (AC ≥ 2, ~1,6М аллельде). 60/20/20 бөлу, ген × белгі стратификациясы. RANDOM_STATE=42.",
        "mc_architecture": "Архитектура",
        "mc_architecture_d": "XGBoost + көп қабатты перцептрон аралас ансамблі, ген-адаптивті салмақтармен және бөлек калибрлеу жиынында изотоникалық калибрлеумен. 8 деректер көзінен 120 инженерлік белгі.",
        "mc_performance": "Өнімділік",
        "mc_performance_d": "ROC-AUC: 0.985 · MCC: 0.928 · Теңгерілген дәлдік: 96.5%. 10-қатпарлы CV: 0.9858 ± 0.0021. REVEL (0.725), BayesDel (0.721), CADD (0.539) асып түседі.*",
        "mc_perf_caveat": "* SteppeDNA тест жиынында бағаланған. Жалпы мақсаттағы құралдар сол таралымда оқытылмаған.",
        "mc_limitations": "Белгілі шектеулер",
        "mc_lim1": "BRCA2-ден басқа гендерде оқыту жиындары аз және ген бойынша AUC төмен (PALB2: 0.605, RAD51C: 0.785)",
        "mc_lim2": "Көшірме саны варианттары (CNV) жіктелмейді. Сплайс-сайт, кадр ішіндегі инделдер және синоним варианттар ереже негізінде жіктеледі (ML моделімен емес). Қысқартатын варианттар Tier 1 хаттамасын пайдаланады",
        "mc_lim3": "Популяция жиілігі деректері жоқ жаңа варианттарда модель нашар жұмыс істеуі мүмкін",
        "mc_lim4": "Ықтималдықтар [1%, 99%] аралығында шектеледі — модель абсолютті сенімділікті мәлімдемейді",
        "mc_lim5": "VCF пакеттік талдауда құрама гетерозиготтылық ескертуі беріледі, бірақ фазалау жүргізілмейді; варианттар цис/транс конфигурациясын анықтау үшін сегрегация зерттеуін қажет етеді",
        "mc_lim6": "Оқыту деректері негізінен еуропалық текті; алайда белгілердің 90.8%-ы популяцияға тәуелсіз. Популяцияға калибрленген ACMG ережелері мен кеңейтілген CI-лар жиілік қиғаулығын азайтады",
        "mc_lim7": "ClinVar жіктелулері уақыт өте өзгереді; оқыту белгілері соңғы сарапшылар консенсусын көрсетпеуі мүмкін",
        "mc_sota_note": "SteppeDNA тест жиынында бағаланған. REVEL, BayesDel және CADD жалпы мақсаттағы болжамшылар. Тәуелсіз бенчмарк AUC: 0.750–0.801 (оқыту қабаттаспайды). Жалпы метрикалар ген таралуына байланысты (BRCA2: тест жиынының 52%).",
        "acmg_approx_label": "Есептеулік жуықтау — валидацияланбаған ACMG жіктелуі. 28 ACMG критерийлерінің 11-ін іске асырады.",
        "gene_reliability_warn": "Ген бойынша модель сенімділігі",
        "vus_guidance": "Бұл вариант белгісіз аймаққа түседі. Ұсыныстар: (1) функционалдық зерттеу валидациясы, (2) отбасылық сегрегация зерттеуі, (3) ClinVar-да қайта жіктелуді бақылау, (4) генетикалық кеңесшімен кеңесу.",
        "population_label": "Популяция",
        "pop_global": "Жаһандық (әдепкі)",
        "founder_badge": "Белгілі негізін қалаушы мутация",
        "founder_freq": "Жиілік",
        "mc_ethics": "Этикалық мәселелер",
        "mc_eth1": "Клиникалық диагностикалық қолдануға валидацияланбаған — барлық болжамдар сарапшы шолуын қажет етеді",
        "mc_eth2": "Оқыту деректері негізінен еуропалық тектен; аз ұсынылған этностар үшін популяцияға калибрленген ACMG ережелері мен кеңейтілген сенімділік аралықтары қолданылады",
        "mc_eth3": "ACMG дәлелдеме кодтары есептеулік жуықтаулар, сарапшы жіктелулер емес",
        "mc_eth4": "Пациенттерге медициналық көмек туралы клиникалық шешімдердің жалғыз негізі ретінде пайдаланылмауы керек",
        "vcf_type_col": "Түрі",
        "splice_canonical": "Канондық сплайс-сайт",
        "splice_near": "Сплайс-сайтқа жақын",
        "inframe_indel": "Кадр ішіндегі инделді",
        "synonymous_label": "Синоним",
        "compound_het_title": "Құрама гетерозиготтылық ескертуі",
        "compound_het_no_gt": "Ескерту: VCF файлында генотип (GT) деректері жоқ. Ескерту вариант санына негізделген.",
        "skipped_title": "Өткізілген варианттар",
        "variants_analyzed": "Жіктелген",
        "umap_title": "Варианттар ландшафты (UMAP)",
        "umap_subtitle": "Сіздің вариантыңыз 5 000 оқыту нұсқасы арасында бағаланған",
        "umap_leg_path": "Патогендік",
        "umap_leg_ben": "Қатерсіз",
        "umap_leg_query": "Сіздің вариант",
        "cmp_title": "Варианттарды салыстыру",
        "offline_msg": "Сервер іске қосылуда — болжамдар жақын арада қолжетімді болады.",
        "online_msg": "Қосылды",
        "viewer3d_title": "3D Ақуыз құрылымы",
        "viewer3d_subtitle": "AlphaFold болжаған құрылымда мутация позициясы белгіленген",
        "viewer3d_loading": "3D құрылым жүктелуде...",
        "viewer3d_error_load": "Бұл ген үшін 3D құрылымды жүктеу мүмкін болмады. Ақуыз браузерде көрсету үшін тым үлкен болуы мүмкін.",
        "viewer3d_error_brca2": "BRCA2 құрылымы (3 418 АҚ) интерактивті браузерде көрсету үшін тым үлкен. Үлкен құрылымдар үшін PyMOL немесе UCSF ChimeraX бағдарламаларын қолданыңыз.",
        "pergene_title": "Ген бойынша ROC-AUC өнімділігі",
        "pergene_footnote": "Жалпы AUC (0.985) тест жиынындағы ген таралуына байланысты өлшенген. BRCA2 тест жиынының 52%-ын құрайды. Стратификацияланған 20% тест жиынында бағаланды.",
        "temporal_footnote": "BRCA2-ден басқа гендердің уақыттық AUC мәндері (0.51–0.61) деректер аз гендер үшін уақыт бойынша жалпылау мүмкіндігінің шектеулі екенін көрсетеді.",
        "ensemble_weights_label": "Ансамбль",
        "ensemble_weights_tip": "XGBoost пен MLP модельдерінің ген-адаптивті қоспасы, калибрлеу деректерінде ген бойынша оңтайландырылған.",
        "feature_coverage_label": "Белгілер қамтуы",
        "feature_coverage_tip": "Осы вариант үшін нөлден өзгеше мәндерге ие 120 модель белгілерінің пайызы. Төменгі қамту аз деректер қолжетімді болғанын білдіреді.",
        "data_support_label": "Оқыту деректерін қолдау",
        "data_support_tip": "Осы вариант позициясына жақын оқыту деректерінің көлемін өлшейді. ЖОҒАРЫ = >100 жақын оқыту варианттары, ОРТАША = 10-100, ТӨМЕН = <10.",
        "data_support_nearby": "жақын",
        "data_support_same_subst": "бірдей алмастыру",
        "data_support_in_domain": "белгілі доменде",
        "data_support_outside_domain": "домен сыртында",
        "bootstrap_ci_label": "Bootstrap CI",
        "bootstrap_ci_tip": "50 bootstrap XGBoost модельдерінен есептелген сенімділік аралығы. Тар CI = сенімдірек болжам. Ені осы вариант маңында оқыту деректерінің тығыздығын көрсетеді.",
        "research_priorities_title": "Зерттеу басымдықтары: Функционалдық валидация үшін ұсынылады",
        "research_priorities_desc": "Варианттар функционалдық валидация үшін маңыздылығы бойынша рангіленген: модельдер арасындағы келіспеушілік, ген деректерінің жетіспеушілігі және позициялық жаңалық.",
        "research_priorities_note": "QBC = Комитет бойынша сұрау (|XGB - MLP|). Басымдық = QBC x ген жетіспеушілігі x позициялық жаңалық.",
        "rp_variant": "Вариант",
        "rp_priority": "Басымдық",
        "rp_qbc": "QBC ұпайы",
        "rp_prediction": "Ағымдағы болжам",
        "rp_nearby": "Жақын оқыту",
        "rp_reason": "Себеп",
        "contrastive_title": "Контрастты тусiндiрме",
        "contrastive_tip": "Қарама-қарсы классификациясы бар ең жақын оқыту вариантын көрсетедi. Негiзгi айырмашылықтар осы вариантты ең жақын қарама-қарсы класс көршiсiнен ең көп ажырататын белгiлердi көрсетедi.",
        "contrastive_compared_to": "Ең жақын",
        "contrastive_variant_word": "вариантпен салыстырғанда",
        "contrastive_predicted": "болжанған",
        "contrastive_differs_in": "бұл вариант ең көп ерекшеленедi",
        "contrastive_distance": "қашықтық",
        "contrastive_query": "Сұраныс",
        "contrastive_contrast": "Контраст",
        "contrastive_imp_high": "Жоғары",
        "contrastive_imp_moderate": "Орташа",
        "contrastive_imp_low": "Төмен",
        "conformal_coverage_label": "90% қамту кепілдігі",
        "conformal_tip": "Бөлінген конформалды болжам шынайы белгіні 90% ықтималдықпен қамтуға кепілдік беретін класстар жиынтығын жасайды (таралудан тәуелсіз). Жалғыз класс — жоғары сенімділік; бірнеше класс — белгісіздікті адал көрсетеді.",
        "conformal_singleton": "Сенімді болжам — конформалды жиынтықта бір класс",
        "conformal_multi": "Белгісіз — конформалды жиынтықта бірнеше класс",
        "sota_comparison_title": "Гендерді SOTA салыстыру",
        "sota_col_gene": "Ген",
        "sota_col_steppdna": "SteppeDNA",
        "sota_col_best_sota": "Үздік SOTA",
        "sota_col_winner": "Жеңімпаз",
        "sota_footnote": "* Барлық құралдар SteppeDNA тест жиынында бағаланған (әдістемелік артықшылық). REVEL/BayesDel/CADD варианттардың 72\u201373% бағалады. Тәуелсіз бенчмарк AUC: 0.750\u20130.801 (оқыту қабаттаспайды).",
        "sota_pergene_note": "Ген бойынша SOTA AUC мәндері SteppeDNA v5.4 тест жиынында бағаланды. Ұпайлар dbNSFP-тен алынды; нұсқаны бағалай алмаған құралдар сол геннің салыстыруынан шығарылды.",
        "method_ml": "МЛ Ансамбль",
        "method_rule": "Ережелерге негізделген",
        "am_title": "AlphaMissense белгі ағып кетуін анықтау",
        "am_explanation": "AlphaMissense (Cheng et al. 2023) ішінара ClinVar белгілерімен оқытылған, бұл жанама белгі циркулярлығын тудырды. Аблация тестілеу AlphaMissense белгілерін жойғаннан кейін 5 геннің 3-інде AUC <strong>жақсарғанын</strong> көрсетті. AlphaMissense v5.4 нұсқасында жойылды.",
        "am_with": "AlphaMissense-пен",
        "am_without": "Онсыз (v5.4)",
        "am_callout": "AlphaMissense жойылғаннан кейін 5 геннің 3-і жақсарды \u2014 жанама ClinVar белгі ағып кетуін растайды. Жалпы AUC: 0.9846 \u2192 0.9853 (жоғалту жоқ).",
        "am_footnote": "Абляция зерттеуі v5.4 алдындағы модель конфигурациясында тек XGBoost-пен жүргізілді. Ген бойынша AUC мәндері соңғы v5.4 XGBoost+MLP ансамблінен ерекшеленеді.",
        "eq_title": "Популяция теңдігін талдау",
        "eq_perf_title": "Шығу тегі бойынша модель өнімділігі",
        "eq_ancestry_caveat": "gnomAD суб-популяция AF бойынша прокси тағайындау \u2014 өз-өзін хабарлаған тек емес. Нұсқалардың 84%-ында популяция анықталмады. Аз іріктеме көлемі интерпретацияны шектейді.",
        "eq_vus_title": "Ген бойынша VUS шешу қабілеті",
        "eq_high": "Жоғары сенімділік",
        "eq_moderate": "Орташа",
        "eq_low": "Төмен \u2014 сақтықпен түсіндіріңіз",
        "eq_pm2_title": "Популяция бойынша PM2 дәлелдемелерінің айырмашылығы",
        "eq_col_pop": "Популяция",
        "eq_col_pm2": "PM2-ге сәйкес варианттар",
        "eq_col_diff": "NFE-ден айырмашылық",
        "eq_footnote": "PM2 (популяция дерекқорларында жоқ) еуропалық емес популяциялар үшін жиі іске қосылады, себебі gnomAD-та олар аз ұсынылған.",
        "eq_mitigation_title": "SteppeDNA популяция қиғаулығын қалай шешеді",
        "eq_mit1": "<strong>90.8% жиілікке тәуелсіз архитектура</strong> \u2014 120 болжау белгісінің 109-ы әмбебап биологиялық сигналдарды пайдаланады (ақуыз құрылымы, эволюциялық консервация, ақуыз тілдік модельдері)",
        "eq_mit2": "<strong>Популяцияға калибрленген ACMG ережелері</strong> \u2014 PM2 дәлелдемесі қазақ/орталық азиялық пациенттер үшін автоматты түрде алынып тасталады. BA1/BS1 шектері 2\u00d7 босатылады",
        "eq_mit3": "<strong>Негізін қалаушы мутация интеграциясы (PS4)</strong> \u2014 7 белгілі қазақ негізін қалаушы мутациясы ресми ACMG күшті патогенді дәлелдеме ретінде танылады",
        "eq_mit4": "<strong>Адал белгісіздік</strong> \u2014 сенімділік аралықтары аз ұсынылған популяциялар үшін автоматты түрде кеңейтіледі (\u00d71.5)",
        "fb_title": "Қазақ негізін қалаушы мутациялар \u2014 Құралдар салыстыруы",
        "fb_col_variant": "Вариант",
        "fb_col_gene": "Ген",
        "fb_col_freq": "Жиілік (ҚЗ)",
        "fb_frameshift": "Frameshift \u2014 N/A (SteppeDNA, REVEL)",
        "fb_splice": "Сплайс сайт \u2014 N/A (SteppeDNA, REVEL)",
        "fb_footnote": "CADD балдары PHRED шкаласында (ықтималдық балдарымен тікелей салыстыруға болмайды). REVEL және BayesDel тек миссенс варианттарды бағалайды; SteppeDNA амин қышқылы енгізуін қажет етеді және frameshift немесе сплайс варианттарын бағалай алмайды. CADD барлық вариант түрлерін бағалай алады.",
        "pop_compare_title": "Популяцияның ACMG дәлелдемелеріне әсері",
        "pop_gained": "Жаңа дәлелдеме (популяцияға тән)",
        "pop_lost": "Жаһандыққа қарағанда жойылған",
        "pop_changed": "Негіздеме өзгерді",
        "pop_no_diff": "ACMG дәлелдемелерінде айырмашылық жоқ",
    },
    "ru": {
        "tagline": "Классификатор вариантов Multi-Gene HR • 120 признаков из 8 источников данных • Эмбеддинги ESM-2 белковой LM • Объяснения SHAP",
        "stat_mcc": "MCC",
        "stat_bal_acc": "Сбаланс. точн.",
        "stat_model": "Ансамбль",
        "stat_genes": "HR генов",
        "upload_title": "Загрузить VCF",
        "tgt_gene_ctx": "Контекст целевого гена",
        "drop_vcf": "Перетащите файл VCF сюда",
        "or_click": "или нажмите для выбора · формат .vcf",
        "manual_entry": "Ручной ввод",
        "tgt_gene": "Целевой ген",
        "cdna_pos": "Позиция кДНК",
        "ref_aa": "Референтная АК",
        "alt_aa": "Альтернативная АК",
        "mut_type": "Тип мутации",
        "mutation": "Мутация",
        "mut_opt": "(необяз.)",
        "analyze_btn": "Анализ варианта",
        "why_shap": "Почему такой прогноз? — Вклад признаков SHAP",
        "acmg_ev": "Доказательства ACMG",
        "pathogenic": "Патогенный",
        "benign": "Доброкачественный",
        "legend_path": "Патогенный",
        "legend_ben": "Доброкачественный",
        "fetch_clinvar": "Данные ClinVar",
        "fetch_gnomad": "Данные gnomAD",
        "vcf_batch": "Результаты пакетного анализа VCF",
        "analyzing": "Анализ вариантов...",
        "tb_hgvs": "HGVS",
        "tb_cdna": "кДНК",
        "tb_aa": "Изменение АК",
        "tb_mut": "Мутация",
        "tb_pred": "Прогноз",
        "tb_prob": "Вероятность",
        "remove_variant": "Удалить вариант",
        "info1_t": "Универсальные базовые модели",
        "info1_d": "Ансамбль глубокой нейронной сети и XGBoost, обученный на 19 000+ миссенс-вариантах ClinVar и gnomAD в генах HR-пути с изотонической калибровкой. Точно классифицирует варианты для 5 генов.",
        "info2_t": "120 признаков",
        "info2_d": "Матрица замен BLOSUM62, эмбеддинги языковой модели ESM-2, функциональные ассаи MAVE, эволюционные оценки EVE, консервация PhyloP, прогнозы сплайсинга SpliceAI, структурные признаки AlphaFold и популяционные частоты gnomAD.",
        "info3_t": "Объяснения SHAP",
        "info3_d": "Для каждого прогноза показано, какие признаки повлияли на классификацию как патогенную или доброкачественную, с использованием значений SHAP из модели XGBoost.",
        "footer1": "Только для научных исследований · Не является диагностическим инструментом · Только герминальные варианты",
        "footer2": "Только герминальные: модель обучена исключительно на наследственных (герминальных) вариантах из ClinVar и gnomAD. Соматические (опухолевые) мутации не поддерживаются.",
        "footer3": "Коды доказательств ACMG являются вычислительным приближением и не заменяют экспертную клиническую курацию.",
        "footer4": "Конфиденциальность: никакие данные о вариантах, запросы или личная информация не сохраняются, не регистрируются и не передаются третьим лицам. Все прогнозы вычисляются на сервере и удаляются после ответа.",
        "err_vcf_only": "Принимаются только файлы .vcf",
        "err_vcf_failed": "Ошибка загрузки VCF",
        "err_backend": "Не удалось подключиться к серверу — убедитесь, что сервер запущен.",
        "err_invalid_ref": "Недопустимая референтная АК",
        "err_invalid_alt": "Недопустимая альтернативная АК",
        "err_cdna_range": "Позиция кДНК должна быть от 1 до",
        "err_enter_cdna": "Пожалуйста, введите позицию последовательности кДНК",
        "err_enter_ref": "Пожалуйста, введите референтную аминокислоту (напр. Arg)",
        "err_enter_alt": "Пожалуйста, введите альтернативную аминокислоту (напр. Cys)",
        "err_timeout": "Время запроса истекло — сервер может быть перегружен. Попробуйте ещё раз.",
        "err_no_results": "Результаты прогноза не получены от сервера.",
        "vcf_processing": "Обработка файла VCF...",
        "vcf_complete": "Анализ VCF завершён",
        "vcf_variants_found": "вариантов проанализировано",
        "download_csv": "Скачать CSV",
        "shap_show_all": "Показать все признаки",
        "shap_show_top": "Только топ 8",
        "download_pdf": "Скачать PDF отчёт",
        "history_title": "Последние анализы",
        "history_clear": "Очистить",
        "download_json": "Экспорт JSON",
        "compare_btn": "Сравнить",
        "stat_sw_auc": "Взвеш. AUC",
        "stat_macro_auc": "Макро-ср. AUC",
        "tip_roc_auc": "Взвешенная по выборке площадь под ROC-кривой. Измеряет, насколько хорошо модель отличает патогенные варианты от доброкачественных. 1.0 = идеально, 0.5 = случайное угадывание. Взвешена по представленности генов (BRCA2 = 52% тестового набора).",
        "tip_macro_auc": "Макро-усреднённый AUC по всем 5 генам (без взвешивания).",
        "tip_mcc": "Коэффициент корреляции Мэтьюса. Сбалансированная метрика от -1 до +1, учитывающая истинно/ложно положительные и отрицательные результаты. Самая надёжная метрика бинарной классификации.",
        "tip_bal_acc": "Среднее чувствительности (доля верно определённых патогенных) и специфичности (доля верно определённых доброкачественных). Не зависит от дисбаланса классов.",
        "tip_ensemble": "XGBoost + многослойный перцептрон с ген-адаптивными весами и изотонической калибровкой. Весовые соотношения оптимизированы для каждого гена на калибровочных данных.",
        "tip_hr_genes": "Гены гомологичной рекомбинации ДНК: BRCA1, BRCA2, PALB2, RAD51C, RAD51D. Мутации в этих генах вызывают наследственный рак молочной железы, яичников и другие виды рака.",
        "tip_ref_aa": "Исходная (дикого типа) аминокислота в данной позиции. Используйте 3-буквенные коды: Ala, Arg, Asn, Asp, Cys, Glu, Gly, His, Ile, Leu, Lys, Met, Phe, Pro, Ser, Thr, Trp, Tyr, Val.",
        "tip_alt_aa": "Мутантная аминокислота, заменившая исходную. Это вариант, который вы хотите классифицировать как патогенный или доброкачественный.",
        "tip_acmg": "Критерии классификации Американской коллегии медицинской генетики. PP/PM/PS = доказательства патогенности. BP/BS/BA = доказательства доброкачественности. Это вычислительные приближения.",
        "tip_shap": "SHAP показывает, как каждый биологический признак повлиял на прогноз в сторону патогенности (+) или доброкачественности (-). Длиннее полоса = сильнее влияние на данный вариант. Примечание: значения SHAP объясняют, какие признаки повлияли на прогноз. Они не подразумевают биологическую причинно-следственную связь.",
        "tip_clinvar": "База данных NCBI ClinVar. Запрашивает актуальную клиническую классификацию данного варианта от лабораторий по всему миру.",
        "tip_gnomad": "База данных агрегации геномов. Показывает частоту встречаемости варианта среди ~807 тыс. секвенированных людей (~1,6 млн аллелей) из различных популяций.",
        "tip_eve": "Эволюционная модель эффекта вариантов. Модель без учителя, обученная на 140 тыс.+ белковых последовательностях. Балл 0-1, >0.5 = вероятно патогенный. Доступна для BRCA1, PALB2, RAD51C, RAD51D.",
        "tip_mave": "Мультиплексный анализ эффектов вариантов. Лабораторное измерение функции белка. Низкий балл = потеря функции = вероятно патогенный.",
        "tip_phylop": "Филогенетическое P-значение, измеряющее эволюционную консервацию среди 100 видов позвоночных. Выше = консервативнее = мутации опаснее.",
        "tip_3d_structure": "3D-структура белка по данным AlphaFold. Показывает, находится ли мутация внутри белка, на поверхности или в контакте с ДНК.",
        "tip_blosum62": "Балл замены аминокислот из матрицы BLOSUM62. Отрицательный = редкая/опасная замена. Положительный = распространённая/безвредная.",
        "tip_volume_diff": "Разница в физическом объёме исходной и мутантной аминокислоты (в кубических ангстремах). Большие изменения нарушают упаковку белка.",
        "tip_hydro_diff": "Разница в гидрофобности (водоотталкивающей способности). Большие изменения могут перевести остаток из скрытого в открытый или наоборот.",
        "tip_charge_change": "Меняет ли мутация электрический заряд аминокислоты (напр. с положительного на отрицательный). Изменения заряда часто нарушают взаимодействия.",
        "tip_nonsense": "Создаёт ли мутация преждевременный стоп-кодон (Ter), усекающий белок. Почти всегда патогенный.",
        "tip_critical_domain": "Находится ли мутация в известном функциональном домене (ДНК-связывающий, PALB2-связывающий, BRC-повторы). Доменные мутации чаще опасны.",
        "mc_title": "Карточка модели и ограничения",
        "mc_intended_use": "Предназначение",
        "mc_intended_use_d": "Классификация миссенс, нонсенс и усекающих вариантов исследовательского уровня в 5 генах гомологичной рекомбинации (BRCA1, BRCA2, PALB2, RAD51C, RAD51D). Миссенс-варианты используют ML-ансамбль; усекающие варианты (фреймшифт, инделы, дупликации) классифицируются протоколом Tier 1. Инструмент поддержки принятия решений, не самостоятельная диагностика.",
        "mc_training_data": "Данные обучения",
        "mc_training_data_d": "19 223 варианта: 18 738 из ClinVar (экспертные классификации) + 485 прокси-доброкачественных из gnomAD (AC ≥ 2 в ~1,6М аллелей). Разделение 60/20/20 со стратификацией по генам × меткам. RANDOM_STATE=42.",
        "mc_architecture": "Архитектура",
        "mc_architecture_d": "Ансамбль XGBoost + многослойный перцептрон с ген-адаптивными весами и изотонической калибровкой на выделенном калибровочном наборе. 120 инженерных признаков из 8 источников данных.",
        "mc_performance": "Производительность",
        "mc_performance_d": "ROC-AUC: 0.985 · MCC: 0.928 · Сбалансированная точность: 96.5%. 10-кратная CV: 0.9858 ± 0.0021. Превосходит REVEL (0.725), BayesDel (0.721), CADD (0.539).*",
        "mc_perf_caveat": "* Оценено на тестовом наборе SteppeDNA. Инструменты общего назначения не обучались на том же распределении.",
        "mc_limitations": "Известные ограничения",
        "mc_lim1": "Гены кроме BRCA2 имеют меньшие обучающие выборки и более низкий AUC (PALB2: 0.605, RAD51C: 0.785)",
        "mc_lim2": "Варианты числа копий (CNV) не классифицируются. Сплайс-сайт, внутрирамочные инделы и синонимичные варианты классифицируются на основе правил (не ML-моделью). Усекающие варианты используют протокол Tier 1",
        "mc_lim3": "Модель может хуже работать на новых вариантах без данных о популяционной частоте",
        "mc_lim4": "Вероятности ограничены диапазоном [1%, 99%] — модель не утверждает абсолютную достоверность",
        "mc_lim5": "Предупреждение о компаунд-гетерозиготности предоставляется в пакетном анализе VCF, но фазирование не выполняется; для определения цис/транс конфигурации необходимо исследование сегрегации",
        "mc_lim6": "Данные обучения преимущественно европейского происхождения; однако 90.8% признаков популяционно-независимы. Калиброванные правила ACMG и расширенные ДИ смягчают смещение частот для центральноазиатских вариантов",
        "mc_lim7": "Классификации ClinVar развиваются; обучающие метки могут не отражать последний экспертный консенсус",
        "mc_sota_note": "Оценено на тестовом наборе SteppeDNA. REVEL, BayesDel и CADD — предикторы общего назначения. Независимый бенчмарк AUC: 0.750–0.801 (без пересечения с обучающими данными). Общие метрики взвешены по распространённости генов (BRCA2: 52% тестового набора).",
        "acmg_approx_label": "Вычислительное приближение — не валидированная ACMG-классификация. Реализует 11 из 28 критериев ACMG.",
        "gene_reliability_warn": "Надёжность модели для гена",
        "vus_guidance": "Этот вариант попадает в зону неопределённости. Рекомендации: (1) валидация функциональным анализом, (2) исследование семейной сегрегации, (3) мониторинг реклассификации в ClinVar, (4) консультация генетического консультанта.",
        "population_label": "Популяция",
        "pop_global": "Глобальная (по умолчанию)",
        "founder_badge": "Известная мутация-основатель",
        "founder_freq": "Частота",
        "mc_ethics": "Этические аспекты",
        "mc_eth1": "Не валидирован для клинической диагностики — все прогнозы требуют экспертной оценки",
        "mc_eth2": "Данные обучения преимущественно европейского происхождения; для недопредставленных этносов применяются калиброванные правила ACMG и расширенные доверительные интервалы",
        "mc_eth3": "Коды доказательств ACMG являются вычислительными приближениями, а не экспертными классификациями",
        "mc_eth4": "Не должен использоваться как единственное основание для клинических решений по лечению пациентов",
        "vcf_type_col": "Тип",
        "splice_canonical": "Канонический сплайс-сайт",
        "splice_near": "Рядом со сплайс-сайтом",
        "inframe_indel": "Внутрирамочный индел",
        "synonymous_label": "Синонимичный",
        "compound_het_title": "Предупреждение о компаунд-гетерозиготности",
        "compound_het_no_gt": "Примечание: VCF-файл не содержал данных генотипа (GT). Предупреждение основано на количестве вариантов.",
        "skipped_title": "Пропущенные варианты",
        "variants_analyzed": "Классифицировано",
        "umap_title": "Ландшафт вариантов (UMAP)",
        "umap_subtitle": "Ваш вариант оценён среди 5 000 обучающих вариантов",
        "umap_leg_path": "Патогенный",
        "umap_leg_ben": "Доброкачественный",
        "umap_leg_query": "Ваш вариант",
        "cmp_title": "Сравнение вариантов",
        "offline_msg": "Сервер запускается — прогнозы будут доступны в ближайшее время.",
        "online_msg": "Подключено",
        "viewer3d_title": "3D Структура белка",
        "viewer3d_subtitle": "Позиция мутации выделена на структуре, предсказанной AlphaFold",
        "viewer3d_loading": "Загрузка 3D структуры...",
        "viewer3d_error_load": "Не удалось загрузить 3D структуру для этого гена. Белок может быть слишком большим для отображения в браузере.",
        "viewer3d_error_brca2": "Структура BRCA2 (3 418 АК) слишком велика для интерактивного отображения в браузере. Используйте PyMOL или UCSF ChimeraX для крупных структур.",
        "pergene_title": "ROC-AUC по генам",
        "pergene_footnote": "Общий AUC (0.985) взвешен по представленности генов. BRCA2 составляет 52% тестового набора. Оценено на стратифицированной 20% тестовой выборке.",
        "temporal_footnote": "Временные AUC для генов кроме BRCA2 (0.51–0.61) указывают на ограниченную обобщаемость во времени для генов с малым объёмом данных.",
        "ensemble_weights_label": "Ансамбль",
        "ensemble_weights_tip": "Ген-адаптивная смесь моделей XGBoost и MLP, оптимизированная по каждому гену на калибровочных данных.",
        "feature_coverage_label": "Покрытие признаков",
        "feature_coverage_tip": "Доля из 120 признаков модели с ненулевыми значениями для данного варианта. Низкое покрытие означает меньше данных, что может снизить надёжность прогноза.",
        "data_support_label": "Поддержка обучающих данных",
        "data_support_tip": "Измеряет объём обучающих данных вблизи позиции варианта. ВЫСОКИЙ = >100 ближайших обучающих вариантов, СРЕДНИЙ = 10-100, НИЗКИЙ = <10.",
        "data_support_nearby": "рядом",
        "data_support_same_subst": "та же замена",
        "data_support_in_domain": "в известном домене",
        "data_support_outside_domain": "вне известного домена",
        "bootstrap_ci_label": "Bootstrap CI",
        "bootstrap_ci_tip": "Доверительный интервал, вычисленный на основе 50 бутстрэп-моделей XGBoost. Узкий CI = более надежный прогноз. Ширина отражает плотность обучающих данных вблизи варианта.",
        "research_priorities_title": "Приоритеты исследований: Рекомендовано для функциональной валидации",
        "research_priorities_desc": "Варианты ранжированы по их ценности для функциональной валидации на основе разногласия моделей, дефицита данных по гену и позиционной новизны.",
        "research_priorities_note": "QBC = Запрос по комитету (|XGB - MLP|). Приоритет = QBC x дефицит гена x позиционная новизна.",
        "rp_variant": "Вариант",
        "rp_priority": "Приоритет",
        "rp_qbc": "Оценка QBC",
        "rp_prediction": "Текущий прогноз",
        "rp_nearby": "Ближайшие обуч.",
        "rp_reason": "Причина",
        "contrastive_title": "Контрастное объяснение",
        "contrastive_tip": "Показывает ближайший обучающий вариант с противоположной классификацией. Ключевые различия выделяют признаки, которые больше всего отличают этот вариант от ближайшего соседа противоположного класса.",
        "contrastive_compared_to": "По сравнению с ближайшим",
        "contrastive_variant_word": "вариантом",
        "contrastive_predicted": "предсказанный",
        "contrastive_differs_in": "этот вариант больше всего отличается в",
        "contrastive_distance": "расстояние",
        "contrastive_query": "Запрос",
        "contrastive_contrast": "Контраст",
        "contrastive_imp_high": "Высокий",
        "contrastive_imp_moderate": "Средний",
        "contrastive_imp_low": "Низкий",
        "conformal_coverage_label": "Гарантия покрытия 90%",
        "conformal_tip": "Раздельное конформное предсказание создаёт набор классов, гарантированно содержащий истинную метку с вероятностью 90% (без предположений о распределении). Один класс = высокая уверенность; несколько классов = честное отражение неопределённости.",
        "conformal_singleton": "Уверенный прогноз — один класс в конформном множестве",
        "conformal_multi": "Неопределённость — несколько классов в конформном множестве",
        "sota_comparison_title": "Погенное сравнение SOTA",
        "sota_col_gene": "Ген",
        "sota_col_steppdna": "SteppeDNA",
        "sota_col_best_sota": "Лучший SOTA",
        "sota_col_winner": "Победитель",
        "sota_footnote": "* Все инструменты оценены на тестовом наборе SteppeDNA (методологическое преимущество). REVEL/BayesDel/CADD оценили 72\u201373% вариантов. Независимый бенчмарк AUC: 0.750\u20130.801 (без пересечения с обучающими данными).",
        "sota_pergene_note": "AUC SOTA по генам оценены на тестовом наборе SteppeDNA v5.4. Оценки из dbNSFP; инструменты, не оценившие вариант, исключены из сравнения по данному гену.",
        "method_ml": "МЛ Ансамбль",
        "method_rule": "На основе правил",
        "am_title": "Обнаружение утечки меток AlphaMissense",
        "am_explanation": "AlphaMissense (Cheng et al. 2023) частично обучен на метках ClinVar, что создаёт косвенную циркулярность меток. Абляционное тестирование показало, что удаление признаков AlphaMissense <strong>улучшило</strong> AUC для 3 из 5 генов. AlphaMissense удалён в v5.4.",
        "am_with": "С AlphaMissense",
        "am_without": "Без (v5.4)",
        "am_callout": "3 из 5 генов улучшились после удаления AlphaMissense \u2014 подтверждает косвенную утечку меток ClinVar. Общий AUC: 0.9846 \u2192 0.9853 (без потерь).",
        "am_footnote": "Абляционное исследование проведено только с XGBoost на конфигурации модели до v5.4. AUC по генам отличаются от финального ансамбля XGBoost+MLP v5.4.",
        "eq_title": "Анализ равенства популяций",
        "eq_perf_title": "Производительность модели по происхождению",
        "eq_ancestry_caveat": "Прокси-назначение по наибольшей AF субпопуляции gnomAD \u2014 не самоидентификация. У 84% вариантов популяция не определена. Малые размеры выборок ограничивают интерпретацию.",
        "eq_vus_title": "Способность разрешения VUS по генам",
        "eq_high": "Высокая достоверность",
        "eq_moderate": "Умеренная",
        "eq_low": "Низкая \u2014 интерпретируйте с осторожностью",
        "eq_pm2_title": "Диспропорция доказательств PM2 по популяциям",
        "eq_col_pop": "Популяция",
        "eq_col_pm2": "Варианты, соответствующие PM2",
        "eq_col_diff": "Отличие от NFE",
        "eq_footnote": "PM2 (отсутствие в популяционных базах) срабатывает чаще для неевропейских популяций из-за их недостаточной представленности в gnomAD.",
        "eq_mitigation_title": "Как SteppeDNA решает проблему популяционного смещения",
        "eq_mit1": "<strong>90.8% признаков независимы от частоты</strong> \u2014 109 из 120 признаков используют универсальные биологические сигналы (структура белка, эволюционная консервация, языковые модели белков)",
        "eq_mit2": "<strong>Популяционно-калиброванные правила ACMG</strong> \u2014 доказательство PM2 автоматически исключается для казахских/центральноазиатских пациентов. Пороги BA1/BS1 ослаблены в 2\u00d7",
        "eq_mit3": "<strong>Интеграция мутаций-основателей (PS4)</strong> \u2014 7 известных казахских мутаций-основателей из опубликованных исследований признаются как формальное сильное патогенное доказательство ACMG",
        "eq_mit4": "<strong>Честная неопределённость</strong> \u2014 доверительные интервалы автоматически расширяются (\u00d71.5) для недопредставленных популяций",
        "fb_title": "Казахские мутации-основатели \u2014 Сравнение инструментов",
        "fb_col_variant": "Вариант",
        "fb_col_gene": "Ген",
        "fb_col_freq": "Частота (КЗ)",
        "fb_frameshift": "Сдвиг рамки \u2014 N/A (SteppeDNA, REVEL)",
        "fb_splice": "Сайт сплайсинга \u2014 N/A (SteppeDNA, REVEL)",
        "fb_footnote": "Баллы CADD по шкале PHRED (не сравнимы напрямую с вероятностными баллами). REVEL и BayesDel оценивают только миссенс-варианты; SteppeDNA требует ввода аминокислоты и не может оценивать сдвиг рамки или сплайс-варианты. CADD может оценивать все типы вариантов.",
        "pop_compare_title": "Влияние популяции на доказательства ACMG",
        "pop_gained": "Новые доказательства (специфичные для популяции)",
        "pop_lost": "Удалено по сравнению с глобальным",
        "pop_changed": "Изменённое обоснование",
        "pop_no_diff": "Нет различий в доказательствах ACMG",
    }
};

let currentLang = localStorage.getItem('lang') || 'en';

function setLang(lang) {
    if (!i18n[lang]) return;
    currentLang = lang;
    localStorage.setItem('lang', lang);
    const d = i18n[lang];
    // Crossfade animation wrapper
    const elementsToUpdate = document.querySelectorAll('[data-i18n]');

    // Fade out
    elementsToUpdate.forEach(el => {
        el.style.opacity = '0';
    });

    // Wait for fade out, swap text, fade in
    setTimeout(() => {
        elementsToUpdate.forEach(el => {
            const key = el.getAttribute('data-i18n');
            if (d[key]) {
                if (el.tagName === 'INPUT') {
                    el.placeholder = d[key];
                } else {
                    // Preserve child elements (e.g. tooltip buttons) when swapping text
                    const childElements = Array.from(el.children);
                    const translationHasHtml = /<[a-z]/i.test(d[key]);
                    if (translationHasHtml) {
                        // Use innerHTML for translations containing HTML markup (e.g. <strong>)
                        el.innerHTML = d[key];
                    } else if (childElements.length > 0) {
                        // Save child elements, replace content, re-append children
                        const savedChildren = childElements.map(c => c.cloneNode(true));
                        el.textContent = d[key] + ' ';
                        savedChildren.forEach(c => el.appendChild(c));
                    } else {
                        el.textContent = d[key];
                    }
                }
            }
            el.style.opacity = '1';
        });

        // Handle the submit button explicitly so it doesn't overwrite spinner text if disabled
        const btnText = document.getElementById('btnText');
        if (btnText && !document.getElementById('submitBtn').disabled) {
            btnText.textContent = d['analyze_btn'];
            btnText.style.opacity = '1';
        }

        // Translate tooltip text spans (data-i18n-tooltip)
        document.querySelectorAll('[data-i18n-tooltip]').forEach(tipEl => {
            const tipKey = tipEl.getAttribute('data-i18n-tooltip');
            if (d[tipKey]) {
                tipEl.textContent = d[tipKey];
            }
        });

    }, 150); // Matches typical fast transition duration

    // Toggle active state on language buttons
    document.querySelectorAll('.lang-btn').forEach(btn => {
        if (btn.dataset.lang === lang) {
            btn.classList.add('active');
        } else {
            btn.classList.remove('active');
        }
    });

    // Ensure initial load doesn't trigger a visual pop
    const btnText = document.getElementById('btnText');
    if (btnText && !document.getElementById('submitBtn').disabled) {
        btnText.textContent = d['analyze_btn'];
    }

    // Notify app.js to re-render dynamic content (result card, history)
    window.dispatchEvent(new Event('langchange'));
}

document.addEventListener('DOMContentLoaded', () => {
    setLang(currentLang);
    document.querySelectorAll('.lang-btn').forEach(btn => {
        btn.addEventListener('click', (e) => {
            setLang(e.target.dataset.lang);
        });
    });
});
